### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by pass13046132** [gp5251/webpack-aliyun-oss#12]
code correct webpack config and then npm run build, throw this error:

compiler.hooks.afterEmit.tapPromise('WebpackAliyunOss', (compilation) => {
                       ^

TypeError: Cannot read property 'afterEmit' of undefined

**Comment by gp5251** [comment]
please check the version of your webpack, this plugin requires version only >= 4

**Comment by gp5251** [comment]
please check the version of your webpack, this plugin requires version only >= 4
