### ISSUE TITLE
【Performance Issue】源码中`fileExists`方法的`get`请求会导致额外的外网流出流量

### ISSUE THREAD

**Issue by ddzy** [gp5251/webpack-aliyun-oss#13]
## Current Behavior

在 `vue-cli` 中使用本插件，在打包上传阿里云之后，发现阿里云统计的 `外网流出流量` 消耗很多，发现是插件源码中的 `fileExists` 方法中的 `get` 请求导致的

## Expected Behavior

如果只是为了判断资源是否已经存在，那么用 `head` 请求是否更合理一些呢？这样可以节省大量的流量损耗

**Comment by gp5251** [comment]
谢谢反馈，已经参考官网方法修改
https://help.aliyun.com/document_detail/146174.html
