### ISSUE TITLE
【Bug Report】非首次上传时会报错：UPLOAD ENDED WITH ERRORS

### ISSUE THREAD

**Issue by ddzy** [gp5251/webpack-aliyun-oss#14]
**"webpack-aliyun-oss": "^0.5.2"**

## Current Behavior

远程 oss 地址：

```text
oss://xxx/official-website/temp/
```

本地插件配置：

```javascript
new AliyunOssPlugin({
          dist: "./official-website/temp/", // 需要上传到oss上的给定文件目录
})
```

### 首次上传时

首次上传的时候，远程的 oss 目录是空的，可以正常上传

### 非首次上传时

之后的每一次上传，即 oss 目录已经存在所有待上传文件的前提下，在上传的过程中部分文件会出现错误提示：

![1](https://user-images.githubusercontent.com/33921398/147644303-6aba2172-23c8-40ca-9495-ec2303238117.png)

并且最终会出现 `UPLOAD ENDED WITH ERRORS` 的错误：

![2](https://user-images.githubusercontent.com/33921398/147644452-55d69b3d-f0d9-464e-9894-16e824a39501.png)

## Expected Behavior

**Comment by ddzy** [comment]
附错误日志（日志中的域名用 `xxx` 代替了）：
[upload.error.log](https://github.com/gp5251/webpack-aliyun-oss/files/7788240/upload.error.log)

**Comment by gp5251** [comment]
看log是socket挂起了，把parallel改到1试试

**Comment by ddzy** [comment]
> 

还是不行
```javascript
new AliyunOssPlugin({
          from: "./dist/**", // 上传那个文件或文件夹  可以是字符串或数组
          dist: "./official-website/", // 需要上传到oss上的给定文件目录
          test: false,
          logToLocal: true,
          parallel: 1,
})
```

**Comment by ddzy** [comment]
> 看log是socket挂起了，把parallel改到1试试

还是不行
```javascript
new AliyunOssPlugin({
          from: "./dist/**", // 上传那个文件或文件夹  可以是字符串或数组
          dist: "./official-website/", // 需要上传到oss上的给定文件目录
          test: false,
          logToLocal: true,
          parallel: 1,
})
```

**Comment by gp5251** [comment]
建议咨询一下阿里云
