### ISSUE TITLE
colors 包作者给代码里加了死循环

### ISSUE THREAD

**Issue by sunchenggit** [gp5251/webpack-aliyun-oss#15]
可以看一下这个连接里的事件，https://www.v2ex.com/t/827224
现在已经是无法使用你的这个包了，打印出的都是乱码

**Comment by gp5251** [comment]
据说官方已经做过处理，回滚到之前版本了。
我这试了下，最高升到1.4.0版本，没有出现乱码。你删掉node_modules重新安装一遍试试。

**Comment by gp5251** [comment]
先关闭了，有问题再开
