### ISSUE TITLE
ali-oss put() need filename not directory

### ISSUE THREAD

**Issue by pandajk** [gp5251/webpack-aliyun-oss#3]
when upload, the ossFilePath is a directory which get from dist.
![image](https://user-images.githubusercontent.com/12078363/63821236-c930ed80-c97e-11e9-9e8f-927b546878af.png)

and from ali-oss, we can see it need a name
![image](https://user-images.githubusercontent.com/12078363/63821314-20cf5900-c97f-11e9-9ec5-430c18877880.png)

**Comment by gp5251** [comment]
never matter, a name can also be a path.
